version: '3.8'
services:
  audit:
    build:
#      context: .
      context: ./app
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:./app
#      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - audit_db

  audit_queue:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: 'php artisan queue:work'
#    depends_on:
#      - audit_db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  audit_db:
    image: mysql:8.0.12
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

networks:
  rabbitmq_go_net:
    driver: bridge
